# Generated by Django 6.0.1 on 2026-04-13 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Janitor', 'Janitor'), ('Coordinator', 'Coordinator')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('CICT', 'CICT'), ('COE', 'COE'), ('CSSP', 'CSSP'), ('COED', 'COED'), ('CIT', 'CIT'), ('VALENCIA HALL', 'VALENCIA HALL'), ('ACTIVITY CENTER', 'ACTIVITY CENTER')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
