# Generated by Django 6.0.1 on 2026-04-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterecord',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(default='TEMP', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
