# Generated by Django 6.0.4 on 2026-05-15 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_wasterecord_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasterecord',
            old_name='total',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='building',
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='alert_level',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='Low', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='area',
            field=models.CharField(choices=[('Alvarado Hall', 'Alvarado Hall'), ('Activity Center', 'Activity Center'), ('Pimentel', 'Pimentel'), ('Athletes Building', 'Athletes Building'), ('CHTM Building', 'CHTM Building'), ('Rizal Park', 'Rizal Park'), ('College of Law', 'College of Law'), ('CON Canteen', 'CON Canteen'), ('Roxas Hall', 'Roxas Hall'), ('Carpio Hall', 'Carpio Hall'), ('BulSU Resto', 'BulSU Resto'), ('Hostel', 'Hostel'), ('E-Library', 'E-Library'), ('SRLC', 'SRLC'), ('CBA Building', 'CBA Building'), ('Heroes Park', 'Heroes Park'), ('Natividad Hall', 'Natividad Hall'), ('Flores Hall', 'Flores Hall'), ('Federizo Hall', 'Federizo Hall'), ('Valencia Hall', 'Valencia Hall'), ('Mendoza Hall', 'Mendoza Hall'), ('CCJE Building', 'CCJE Building'), ('Campus 2', 'Campus 2'), ('Student Lounge', 'Student Lounge')], default='Alvarado Hall', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='report_photos/'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Waste', 'Waste')], default='Waste', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
