# Generated by Django 6.0.4 on 2026-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_total_wasterecord_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='coordinator_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='coordinator_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
