# Generated by Django 6.0.1 on 2026-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_wasterecord_coordinator_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Coordinator', 'Coordinator'), ('Janitor', 'Janitor')], max_length=20),
        ),
    ]
