# Generated by Django 6.0.1 on 2026-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='area',
            name='status',
        ),
    ]
