# Generated by Django 6.0.1 on 2026-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_rename_area_name_area_name_remove_area_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='area_name',
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
