# Generated by Django 6.0.1 on 2026-05-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_rename_name_area_area_name_area_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.area'),
        ),
    ]
