# Generated by Django 6.0.1 on 2026-05-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_generatedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.area'),
        ),
    ]
