# Generated by Django 6.0.1 on 2026-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_wasterecord_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='waste_type',
            field=models.CharField(choices=[('Waste With Plastic', 'Waste With Plastic'), ('Plastic Only', 'Plastic Only'), ('Waste Without Plastic', 'Waste Without Plastic')], max_length=30),
        ),
    ]
