# Generated by Django 6.0.1 on 2026-05-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_wasterecord_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_guideline', models.TextField(blank=True)),
                ('moderate_guideline', models.TextField(blank=True)),
                ('high_guideline', models.TextField(blank=True)),
                ('critical_guideline', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_max', models.FloatField(default=4.0)),
                ('moderate_max', models.FloatField(default=7.0)),
                ('high_max', models.FloatField(default=10.0)),
            ],
        ),
    ]
