# Generated by Django 6.0.1 on 2026-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_profile_role_deanmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdsettings',
            name='reporting_period',
            field=models.CharField(choices=[('Today', 'Today'), ('This Week', 'This Week'), ('This Month', 'This Month'), ('This Year', 'This Year')], default='Today', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
