# Generated by Django 6.0.2 on 2026-09-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_thresholdsettings_reporting_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
