# Generated by Django 6.0.1 on 2026-09-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
