# Generated by Django 6.0.1 on 2026-09-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auditlog_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='feedback',
            new_name='content',
        ),
    ]
