# Generated by Django 6.0.7 on 2026-09-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_rename_feedback_auditlog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Wrote Waste Record Feedback', 'Wrote Waste Record Feedback'), ('Edited Waste Record Feedback', 'Edited Waste Record Feedback'), ('Sent Advisory Message', 'Sent Advisory Message'), ('Submitted Waste Record', 'Submitted Waste Record'), ('Edited Waste Record', 'Edited Waste Record'), ('Deleted Waste Record', 'Deleted Waste Record')], max_length=50),
        ),
    ]
