# Generated by Django 6.0.1 on 2026-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_auditlog_waste_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='waste_record_id_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
